### ISSUE TITLE
VISCA over IP support

### ISSUE THREAD

**Issue by alessionossa** [glikely/obs-ptz#1]
I think **VISCA over IP** doesn’t need any explanation.

Any way we can help bring support for this essential feature?

**Comment by glikely** [comment]
It is certainly on my to-do list, but I've not had a great amount of time to work on the plugin over the past several months.

I would certainly appreciate any help getting VISCA over IP enabled.

**Comment by alessionossa** [comment]
Great! I'll see what I can do in the next few weeks.

If you can provide a little explanation on how the code is structured at the moment, it would make the work easier!

**Comment by glikely** [comment]
I've just pushed an update that will make things easier by removing most of libvisca and replacing it with local code. The ViscaInterface class implements all the interaction with the camera. You could implement IP support by replacing/subclassing ViscaInterface with one that uses a network connection instead of QSerialPort

**Comment by glikely** [comment]
Initial implementation of VISCA-over-IP is now in pushed to the visca-over-ip-test branch
