### ISSUE TITLE
Support OBS 28.0

### ISSUE THREAD

**Issue by iesv** [glikely/obs-ptz#104]

**Comment by bpmacedo** [comment]
+1 here

Thx 4 the support!!!

**Comment by hmsjel** [comment]
Is there comming an update to  OBS 28

**Comment by pviall** [comment]
Another one who updated OBS before I should have...

**Comment by palaniappan1989** [comment]
+1 
Thanks for the support.

**Comment by glikely** [comment]
Hi all. I've pushed out experimental support for v28. It has only been tested on an Apple Silicon Mac. Linux and x86 Mac have been built, but not tested. Windows builds are not yet working. Also connection over serial is disabled because the QSerialPort library is missing.

Images aren't available yet. I need to do some more work on the build environment to get those working.

The changes to Qt6 required moving up to the latest version of the obs-plugintemplate, but my code had deviated enough that it broke how additional libraries are brought in. QGamePad is gone entirely, and QSerialPort needs to be re-integrated.

**Comment by ThomasConnolly** [comment]
Thanks, glikely, for the work you put into this plugin. I wish I could help, but I'm not a coder.

**Comment by glikely** [comment]
Fixed in v0.12.0-pre5
