### ISSUE TITLE
v0.7.0-rc1: Save preset and clear preset do not behave as expected

### ISSUE THREAD

**Issue by iesvme** [glikely/obs-ptz#36]
1. Right click PTZ Controls bar does not respond, no menu.
2. "Save presets" and "Clear presets" don't work. It cannot delete selected one.
3. Cameras bar has no right click menu.

**Comment by glikely** [comment]
What kind of camera are you using? Is it connecting over PELCO-P or VISCA?

**Comment by iesvme** [comment]
sorry, I mean just here:
![image](https://user-images.githubusercontent.com/16969250/131242225-4be6edfc-b430-4719-ae34-21b39cfe2b17.png)


> What kind of camera are you using? Is it connecting over PELCO-P or VISCA?

**Comment by glikely** [comment]
Thanks for the bug report. A right-click context menus has not been implemented in the camera list, which is why you're not seeing one. 😄 

What are you expecting from "save preset" and "clear preset"? The way the plugin currently works there are a fixed number of presets named "Preset 1" to "Preset 16". Save preset and clear preset doesn't change the number of presets in the list. Instead, save preset updates the selected preset with the current camera position, and clear preset resets the name and tells the camera to forget the preset position.

**Comment by iesvme** [comment]
> Thanks for the bug report. A right-click context menus has not been implemented in the camera list, which is why you're not seeing one. 😄
> 
> What are you expecting from "save preset" and "clear preset"? The way the plugin currently works there are a fixed number of presets named "Preset 1" to "Preset 16". Save preset and clear preset doesn't change the number of presets in the list. Instead, save preset updates the selected preset with the current camera position, and clear preset resets the name and tells the camera to forget the preset position.

Oh, now I see. That's a good way of it. I thought it would pop up a dialog to save the preset file on the computer or clear the preset file. Bye the way, if I needn't use 16 presets, how can I delete them?

**Comment by glikely** [comment]
> Oh, now I see. That's a good way of it. I thought it would pop up a dialog to save the preset file on the computer or clear the preset file. Bye the way, if I needn't use 16 presets, how can I delete them?

Right now you can't. The list is fixed because that was the easiest way to implement it while managing the limited number of save slots on the camera. However, I do think it would be better to be able to dynamically add/remove presets and let the plugin manage the preset number, or even store the position in the configuration file for cameras that don't have preset save slots. There is already an issue tracking this.

#24

**Comment by iesvme** [comment]
Thank you very much! I am expecting the next version to be released.
