### ISSUE TITLE
Feature Request: Camera Slider Controls

### ISSUE THREAD

**Issue by Nafru** [glikely/obs-ptz#81]
I am in the process of building a two axis camera slider for streaming aquariums, using a Raspberry Pi, Arduino, GRBLSheild and Stepper motors. 

Is it possible to build in simple G-code moves and set locations in the OBS PTZ software?

**Comment by glikely** [comment]
A G-code backend would not be difficult to add. It is just another protocol. I'm happy to add it if someone writes the code and can test.

**Comment by playaspec** [comment]
> Is it possible to build in simple G-code moves and set locations in the OBS PTZ software?

Why not give the slider a VISCA interface? Then it would be compatible with a _**WIDE**_ variety of professional and prosumer gear. There's a number of exiting VISCA libraries for both Arduino and  Linux.

**Comment by glikely** [comment]
I'm closing this issue for now. I'd be happy to add slider support, but I agree wit @playaspec's suggestion. If you can make it receive VISCA commands then it will work out of the box. VISCA doesn't have a slider command, but you could reuse the pan/tilt command so that it maps to the existing buttons. The VISCA pan/command is the following bytes over the serial port:

```
Up        81010601vv ww0301FF
Down      81010601vv ww0302FF
Left      81010601vv ww0103FF
Right     81010601vv ww0203FF
UpLeft    81010601vv ww0101FF
UpRight   81010601vv ww0201FF
DownLeft  81010601vv ww0102FF
DownRight 81010601vv ww0202FF
Stop      81010601vv ww0303FF

vv := pan speed, 0x01..0x18
ww := tilt speed, 0x01..0x14
```
